In [ ]:
import numpy as np

In [ ]:
l1=[1,2,3,4]
arry=np.array(l1)
print(arry)

[1 2 3 4]


In [ ]:
l2=[11,22,33,44]
l2

[11, 22, 33, 44]

In [ ]:
l=[l1,l2]
l

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [ ]:
array_2D=np.array(l)
array_2D

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [ ]:
array_2D.shape

(2, 4)

In [ ]:
np.zeros(3,'int')

array([0, 0, 0])

In [ ]:
array_2D.dtype

dtype('int64')

In [ ]:
list1=[1,2,3,3]
print( list1)
myArray=np.array(list1)
print(myArray)

[1, 2, 3, 3]
[1 2 3 3]


In [ ]:
list1=[1,2,3,3]
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros(3)
np.empty(3)

array([0., 0., 0.])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
listt=[list1,list2]
print(listt)
myArry=np.array(listt)
print(myArry)


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr1=np.array([[1,2,3,4],[8,9,10,11]])
print(arr1)

[[ 1  2  3  4]
 [ 8  9 10 11]]


In [ ]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [ ]:
arr1**3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

In [ ]:
arr1**4

array([[    1,    16,    81,   256],
       [ 4096,  6561, 10000, 14641]])

In [ ]:
arr1-2

array([[-1,  0,  1,  2],
       [ 6,  7,  8,  9]])

In [ ]:
arr1.T

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11]])

In [ ]:
A=np.array([[1,2,3],[4,5,6]])
print(A)
print('\n')
B=np.array([[7,8],[9,10],[11,12]])
print(B)
print('\n')
np.dot(A,B)

[[1 2 3]
 [4 5 6]]


[[ 7  8]
 [ 9 10]
 [11 12]]




array([[ 58,  64],
       [139, 154]])

In [ ]:
import numpy as np


In [ ]:
array1 = np.array([1, 3, 5])
array2 = np.array([2, 4, 6])

print("Multiplication: " ,array1 * array2)
print("Addition: ",array1 + array2)
print("Subtraction: ",array1 - array2)
print("Division: ",array1 / array2)


Multiplication:  [ 2 12 30]
Addition:  [ 3  7 11]
Subtraction:  [-1 -1 -1]
Division:  [0.5        0.75       0.83333333]


In [ ]:
arr=[1,2,3,4,5,6,7,8,9,10]
arr[3:6]

[4, 5, 6]

In [ ]:

arr=[1,2,3,4,5,6,7,8,9,10]
arr[0:5] = [22]
arr


[22, 6, 7, 8, 9, 10]

In [ ]:
arr=[1,2,3,4,5,6,7,8,9,10]
arr[0:0] =[99]
arr

[99, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
arr[0]

99

In [ ]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[1]

array([20, 25, 30])

In [ ]:
arr_2d[:,1]

array([10, 25, 40])

In [ ]:
arr_2d[:3,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [ ]:
grid = np.arange(1, 13).reshape((3, 4))
grid

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
grid=grid.reshape((4,3))
grid

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
x = np.array([1, 2, 3])
x[::2]

array([1, 3])

In [ ]:
x[2::]

array([3])

In [ ]:
np.concatenate([grid,grid])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([grid,grid],axis=1)


array([[ 1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5,  6],
       [ 7,  8,  9,  7,  8,  9],
       [10, 11, 12, 10, 11, 12]])

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) #split at index 3 &5
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
grid = np.arange(16).reshape((4, 4))
print(grid)
print("\n")
upper, lower = np.vsplit(grid, [2])
print(upper)
print("\n")
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
grid = np.arange(16).reshape((4, 4))
print(grid)
print("\n")
left, right = np.hsplit(grid, [2])
print(left)
print("\n")
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
import numpy as np


In [ ]:
grade=np.array([
               [87,96,55],
               [45,89,96],
               [34,76,88],
               [32,44,78]
               ])
avg=np.mean(grade, axis=1)
print("The Average Grade of Each Student: ",avg)
mx=np.max(grade, axis=0)
print("Highes Grade in Each Subject: ",mx)
ov=np.mean(grade)
print("Overall Average: ",ov)





The Average Grade of Each Student:  [79.33333333 76.66666667 66.         51.33333333]
Highes Grade in Each Subject:  [87 96 96]
Overall Average:  68.33333333333333


In [ ]:
import numpy as np
from numpy.random import randn

In [ ]:
A= np.array([1,2,3,4])
B= np.array([100,200,300,400])

condition=np.array([True,True,False,False])
answer2=np.where(condition,A,B)

answer2

array([  1,   2, 300, 400])

In [ ]:
arr = randn(5,5)

arr

array([[-1.11638335, -0.35076581, -0.94223743, -1.5568524 ,  1.61796872],
       [-0.01052615,  1.62137634,  0.5487442 ,  0.92451705, -0.01496358],
       [-0.77414435,  1.39622797,  0.11437341, -0.02175708,  0.1179063 ],
       [ 0.06238056, -0.02217484, -1.71121332,  1.36976427, -0.35156043],
       [-0.60271183,  1.66633181, -0.03486254,  0.17904336, -0.71318948]])

In [ ]:
np.where(arr < 0,0,arr)

array([[0.        , 0.        , 0.        , 0.        , 1.61796872],
       [0.        , 1.62137634, 0.5487442 , 0.92451705, 0.        ],
       [0.        , 1.39622797, 0.11437341, 0.        , 0.1179063 ],
       [0.06238056, 0.        , 0.        , 1.36976427, 0.        ],
       [0.        , 1.66633181, 0.        , 0.17904336, 0.        ]])

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
print(arr.sum(1))
print(arr.sum(0))

[ 6 15 24]
[12 15 18]


In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.var()

np.float64(6.666666666666667)

In [ ]:
arr.all()

np.True_

In [ ]:
arr.any()

np.True_

In [ ]:
A=np.array([-2,5,4,-8,0])
print(A)

[-2  5  4 -8  0]


In [ ]:
print(np.sort(A)) #Ascending
print(- np.sort(-A)) #Descending

[-8 -2  0  4  5]
[ 5  4  0 -2 -8]


In [ ]:
countries = np.array(['France', 'Germany', 'USA','Russia','USA','Mexico','Germany'])
np.unique(countries)

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'], dtype='<U7')

In [ ]:
np.in1d(['France','USA','Sweden'],countries)

<ipython-input-19-e2b7df327379>:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(['France','USA','Sweden'],countries)


array([ True,  True, False])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.save("my_arr",arr)

In [ ]:
import pandas as pd

In [ ]:
series=pd.Series([10,20,50,40],index=["Apple","Banana","Mango","Strawberry"])
print(series)

Apple         10
Banana        20
Mango         50
Strawberry    40
dtype: int64


In [ ]:
series=pd.Series({"Apple":100,
                  "Banana":100,
                  "Mango":400,
                  "Strawberry":300})
print(series)

Apple         100
Banana        100
Mango         400
Strawberry    300
dtype: int64


In [ ]:
print(series[0])

100


<ipython-input-27-16ea588ce37b>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series[0])


In [ ]:
print(series['Mango'])

400


In [ ]:
print(series[series>300])

Mango    400
dtype: int64


In [ ]:
gro=pd.Series({"Milk":120,"Bread":80,"Eggs":200,"Cheese":150,"Butter":90})
print(gro.sum())
print(gro.max())

640
200


In [ ]:
sales = pd.Series({'Shampoo': 150, 'Soap': 90, 'Toothpaste': 180, 'Lotion': 120})
sales["Soap"]=100
print(sales[sales>120])


Shampoo       150
Toothpaste    180
dtype: int64


In [ ]:
data=pd.read_csv("/content/sales_data.csv")
dataAsSeries=pd.Series(data['Sales'].values,index=data["Month"],name="Sales")
print(dataAsSeries)

Month
January     1200
February    1500
March        800
April        950
Name: Sales, dtype: int64


In [ ]:
fruit=pd.read_csv("/content/Fruits.csv")
print(fruit)


       Fruits  Prices
0       Apple     3.5
1      Banana     1.2
2      Orange     2.0
3  Strawberry     5.5
4      Grapes     2.5
5   Pineapple     4.0
6       Mango     3.0
7   Blueberry     7.0
8       Peach     3.8
9  Watermelon     1.5


In [ ]:
fruit=pd.read_csv("/content/Fruits.csv")
dataFruit=pd.Series(fruit['Fruits'].values,index=fruit["Prices"],name="fruits")
print(dataFruit)


Prices
3.5         Apple
1.2        Banana
2.0        Orange
5.5    Strawberry
2.5        Grapes
4.0     Pineapple
3.0         Mango
7.0     Blueberry
3.8         Peach
1.5    Watermelon
Name: fruits, dtype: object


In [ ]:
emp=pd.read_csv("/content/employees.csv")
print(emp)

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30   Chicago   80000
2  Charlie   28    Boston   75000


In [ ]:
print(emp.head())

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30   Chicago   80000
2  Charlie   28    Boston   75000


In [ ]:
print(emp.tail())

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30   Chicago   80000
2  Charlie   28    Boston   75000


In [ ]:
emp.shape

(3, 4)

In [ ]:
emp.columns

Index(['Name', 'Age', 'City', 'Salary'], dtype='object')

In [ ]:
print(emp.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
 3   Salary  3 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 228.0+ bytes
None


In [ ]:
print(emp.describe())

             Age   Salary
count   3.000000      3.0
mean   27.666667  75000.0
std     2.516611   5000.0
min    25.000000  70000.0
25%    26.500000  72500.0
50%    28.000000  75000.0
75%    29.000000  77500.0
max    30.000000  80000.0


In [ ]:
print(emp['Name'])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object


In [ ]:
emp[['Name','City']]

Name      City
0    Alice  New York
1      Bob   Chicago
2  Charlie    Boston

In [ ]:
emp[emp['Salary']>75000]

Name  Age     City  Salary
1  Bob   30  Chicago   80000

In [ ]:
bonus=emp['Bonus']=emp['Salary']*0.1
print(bonus)

0    7000.0
1    8000.0
2    7500.0
Name: Salary, dtype: float64


In [ ]:
age=emp["Age"]=emp["Age"]+1
print(age)

0    27
1    32
2    30
Name: Age, dtype: int64


In [ ]:
rename=emp.rename(columns={'Salary': 'Income'},
inplace=True)
print(rename)

None


In [ ]:
pr=pd.read_csv("/content/disney_princess_popularity_dataset_300_rows.csv")
print(pr)

    PrincessName         FirstMovieTitle  FirstMovieYear  MovieRuntimeMinutes  \
0     Pocahontas  Pocahontas's Adventure            1977                   85   
1          Mulan       Mulan's Adventure            1995                   85   
2           Raya        Raya's Adventure            1989                  110   
3           Anna        Anna's Adventure            1940                   78   
4          Mulan       Mulan's Adventure            1943                  103   
..           ...                     ...             ...                  ...   
295       Merida      Merida's Adventure            2001                   95   
296        Belle       Belle's Adventure            2006                   76   
297         Anna        Anna's Adventure            2020                   70   
298        Tiana       Tiana's Adventure            1937                   71   
299        Mulan       Mulan's Adventure            1938                  105   

     NumberOfSongs HasSoloS

In [ ]:
print(pr.head())

  PrincessName         FirstMovieTitle  FirstMovieYear  MovieRuntimeMinutes  \
0   Pocahontas  Pocahontas's Adventure            1977                   85   
1        Mulan       Mulan's Adventure            1995                   85   
2         Raya        Raya's Adventure            1989                  110   
3         Anna        Anna's Adventure            1940                   78   
4        Mulan       Mulan's Adventure            1943                  103   

   NumberOfSongs HasSoloSong HasDuet HairColor EyeColor OutfitPrimaryColor  \
0              4          No     Yes     Brown    Green               Pink   
1              1         Yes     Yes    Blonde    Brown             Purple   
2              4          No      No    Blonde    Hazel               Pink   
3              1          No      No     Brown     Grey              Green   
4              7          No     Yes     White    Brown              Green   

   ... RottenTomatoesScore BoxOfficeMillions AvgScreenTi

In [ ]:
print(pr.describe())

       FirstMovieYear  MovieRuntimeMinutes  NumberOfSongs  IMDB_Rating  \
count      300.000000           300.000000     300.000000   300.000000   
mean      1980.243333            90.913333       3.993333     7.466667   
std         24.621227            11.726502       2.149890     0.863311   
min       1937.000000            70.000000       1.000000     6.000000   
25%       1959.750000            80.000000       2.000000     6.700000   
50%       1983.000000            91.000000       4.000000     7.400000   
75%       2000.250000           101.000000       6.000000     8.200000   
max       2021.000000           110.000000       7.000000     9.000000   

       RottenTomatoesScore  BoxOfficeMillions  AvgScreenTimeMinutes  \
count           300.000000         300.000000            300.000000   
mean             80.650000         700.843333             40.616667   
std              10.996237         346.922618             11.575680   
min              60.000000         101.000000    

In [ ]:
print(pr.tail())

    PrincessName     FirstMovieTitle  FirstMovieYear  MovieRuntimeMinutes  \
295       Merida  Merida's Adventure            2001                   95   
296        Belle   Belle's Adventure            2006                   76   
297         Anna    Anna's Adventure            2020                   70   
298        Tiana   Tiana's Adventure            1937                   71   
299        Mulan   Mulan's Adventure            1938                  105   

     NumberOfSongs HasSoloSong HasDuet HairColor EyeColor OutfitPrimaryColor  \
295              7         Yes      No       Red     Grey             Purple   
296              1         Yes      No       Red    Green             Yellow   
297              2          No     Yes     White     Blue               Blue   
298              7          No      No       Red     Blue             Purple   
299              3          No      No     Brown    Brown             Purple   

     ... RottenTomatoesScore BoxOfficeMillions AvgScreen

In [ ]:
print(pr.columns)

Index(['PrincessName', 'FirstMovieTitle', 'FirstMovieYear',
       'MovieRuntimeMinutes', 'NumberOfSongs', 'HasSoloSong', 'HasDuet',
       'HairColor', 'EyeColor', 'OutfitPrimaryColor', 'OutfitStyleEra',
       'IsRoyalByBirth', 'HasAnimalSidekick', 'SidekickType',
       'HasMagicalPowers', 'MagicType', 'MainSetting', 'IsBasedOnRealStory',
       'CulturalOrigin', 'SpeaksToAnimals', 'FightsVillainDirectly',
       'RomanticSubplot', 'MarriedByEnd', 'VillainName', 'VillainType',
       'IMDB_Rating', 'RottenTomatoesScore', 'BoxOfficeMillions',
       'AvgScreenTimeMinutes', 'NumMerchItemsOnAmazon',
       'GoogleSearchIndex2024', 'InstagramFanPages',
       'TikTokHashtagViewsMillions', 'Top3Hashtags', 'IsIconic',
       'PopularityScore'],
      dtype='object')


In [ ]:
print(pr.shape)

(300, 36)


In [ ]:
print(pr.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   PrincessName                300 non-null    object 
 1   FirstMovieTitle             300 non-null    object 
 2   FirstMovieYear              300 non-null    int64  
 3   MovieRuntimeMinutes         300 non-null    int64  
 4   NumberOfSongs               300 non-null    int64  
 5   HasSoloSong                 300 non-null    object 
 6   HasDuet                     300 non-null    object 
 7   HairColor                   300 non-null    object 
 8   EyeColor                    300 non-null    object 
 9   OutfitPrimaryColor          300 non-null    object 
 10  OutfitStyleEra              300 non-null    object 
 11  IsRoyalByBirth              300 non-null    object 
 12  HasAnimalSidekick           300 non-null    object 
 13  SidekickType                230 non

In [ ]:
pr[pr['FirstMovieYear']<1999]

PrincessName         FirstMovieTitle  FirstMovieYear  MovieRuntimeMinutes  \
0     Pocahontas  Pocahontas's Adventure            1977                   85   
1          Mulan       Mulan's Adventure            1995                   85   
2           Raya        Raya's Adventure            1989                  110   
3           Anna        Anna's Adventure            1940                   78   
4          Mulan       Mulan's Adventure            1943                  103   
..           ...                     ...             ...                  ...   
291   Cinderella  Cinderella's Adventure            1964                   82   
292         Anna        Anna's Adventure            1956                   95   
293        Moana       Moana's Adventure            1961                   96   
298        Tiana       Tiana's Adventure            1937                   71   
299        Mulan       Mulan's Adventure            1938                  105   

     NumberOfSongs HasSoloSong HasDuet HairColor EyeColor OutfitPrimaryColor  \
0                4          No     Yes     Brown    Green               Pink   
1                1         Yes     Yes    Blonde    Brown             Purple   
2                4          No      No    Blonde    Hazel               Pink   
3                1          No      No     Brown     Grey              Green   
4                7          No     Yes     White    Brown              Green   
..             ...         ...     ...       ...      ...                ...   
291              2         Yes     Yes     Black    Brown             Purple   
292              3          No      No    Blonde     Blue              Green   
293              4         Yes      No     Black     Grey               Pink   
298              7          No      No       Red     Blue             Purple   
299              3          No      No     Brown    Brown             Purple   

     ... RottenTomatoesScore BoxOfficeMillions AvgScreenTimeMinutes  \
0    ...                  88               661                   25   
1    ...                  91               688                   52   
2    ...                  76               790                   54   
3    ...                  70               820                   42   
4    ...                  86               996                   55   
..   ...                 ...               ...                  ...   
291  ...                  89               397                   44   
292  ...                  93               578                   59   
293  ...                  78               729                   50   
298  ...                  86               463                   54   
299  ...                  77               195                   42   

    NumMerchItemsOnAmazon GoogleSearchIndex2024 InstagramFanPages  \
0                    2524                    68               298   
1                    4202                    49               133   
2                     525                    68               129   
3                    1951                    73               138   
4                    3958                    34               155   
..                    ...                   ...               ...   
291                   493                    61               156   
292                   523                    46                91   
293                  4350                    74               241   
298                  2365                    35               116   
299                  2218                    89                11   

    TikTokHashtagViewsMillions  \
0                          481   
1                          619   
2                          230   
3                          697   
4                          200   
..                         ...   
291                        237   
292                        140   
293                        977   
298                        584   
299           

In [ ]:
print(pr['NumberOfSongs'])

0      4
1      1
2      4
3      1
4      7
      ..
295    7
296    1
297    2
298    7
299    3
Name: NumberOfSongs, Length: 300, dtype: int64


In [ ]:
pr[pr["EyeColor"]=="Green"]

PrincessName         FirstMovieTitle  FirstMovieYear  MovieRuntimeMinutes  \
0     Pocahontas  Pocahontas's Adventure            1977                   85   
13          Raya        Raya's Adventure            1963                  105   
21         Moana       Moana's Adventure            2021                  101   
36        Merida      Merida's Adventure            1962                  109   
43         Mulan       Mulan's Adventure            1974                   72   
47        Merida      Merida's Adventure            2012                   89   
53         Tiana       Tiana's Adventure            1991                   71   
59          Anna        Anna's Adventure            1991                  105   
62       Jasmine     Jasmine's Adventure            1973                  108   
64      Rapunzel    Rapunzel's Adventure            1961                   91   
65          Elsa        Elsa's Adventure            1998                   76   
84         Tiana       Tiana's Adventure            1944                   89   
89    Pocahontas  Pocahontas's Adventure            2013                   70   
91         Belle       Belle's Adventure            1991                  104   
93         Moana       Moana's Adventure            1950                   75   
97        Aurora      Aurora's Adventure            2002                  101   
107        Tiana       Tiana's Adventure            2018                   80   
116         Raya        Raya's Adventure            1975                  106   
125        Moana       Moana's Adventure            1999                   75   
126     Rapunzel    Rapunzel's Adventure            2017                   77   
135         Anna        Anna's Adventure            1995                   87   
136        Mulan       Mulan's Adventure            2003                   85   
138         Anna        Anna's Adventure            1972                   76   
142       Merida      Merida's Adventure            1961                   75   
156         Elsa        Elsa's Adventure            1963                  109   
168   Cinderella  Cinderella's Adventure            1955                   89   
169        Mulan       Mulan's Adventure            1972                  107   
170      Jasmine     Jasmine's Adventure            1991                   95   
180      Jasmine     Jasmine's Adventure            2000                   70   
181         Elsa        Elsa's Adventure            1965                   78   
182        Belle       Belle's Adventure            2003                   93   
183         Elsa        Elsa's Adventure            1999                  103   
184        Mulan       Mulan's Adventure            1987                   94   
188         Anna        Anna's Adventure            1983                   71   
193         Raya        Raya's Adventure            1956                   71   
207       Aurora      Aurora's Adventure            1945                   78   
211        Moana       Moana's Adventure            2017                  100   
217        Tiana       Tiana's Adventure            1983                   74   
219     Rapunzel    Rapunzel's Adventure            1949                   72   
221         Anna        Anna's Adventure            1992                   75   
223         Raya        Raya's Adventure            1971                   99   
224        Belle       Belle's Adventure            1964                  100   
243        Ariel       Ariel's Adventure            1948                  102   
247        Belle       Belle's Adventure            2010                   96   
248     Rapunzel    Rapunzel's Adventure            2017                   93   
252        Moana       Moana's Adventure            1969                   75   
257        Tiana       Tiana's Adventure            1989                   79   
258      Jasmine     Jasmine's Adventure            1951                   90   
260         Anna        Anna's Adve

In [ ]:
pr[pr["IsIconic"]=="Yes"]

PrincessName         FirstMovieTitle  FirstMovieYear  MovieRuntimeMinutes  \
0     Pocahontas  Pocahontas's Adventure            1977                   85   
1          Mulan       Mulan's Adventure            1995                   85   
3           Anna        Anna's Adventure            1940                   78   
4          Mulan       Mulan's Adventure            1943                  103   
5        Jasmine     Jasmine's Adventure            2010                   78   
..           ...                     ...             ...                  ...   
290        Moana       Moana's Adventure            1952                   78   
291   Cinderella  Cinderella's Adventure            1964                   82   
292         Anna        Anna's Adventure            1956                   95   
293        Moana       Moana's Adventure            1961                   96   
297         Anna        Anna's Adventure            2020                   70   

     NumberOfSongs HasSoloSong HasDuet HairColor EyeColor OutfitPrimaryColor  \
0                4          No     Yes     Brown    Green               Pink   
1                1         Yes     Yes    Blonde    Brown             Purple   
3                1          No      No     Brown     Grey              Green   
4                7          No     Yes     White    Brown              Green   
5                7         Yes     Yes     Brown     Blue               Blue   
..             ...         ...     ...       ...      ...                ...   
290              2         Yes     Yes       Red    Brown              Green   
291              2         Yes     Yes     Black    Brown             Purple   
292              3          No      No    Blonde     Blue              Green   
293              4         Yes      No     Black     Grey               Pink   
297              2          No     Yes     White     Blue               Blue   

     ... RottenTomatoesScore BoxOfficeMillions AvgScreenTimeMinutes  \
0    ...                  88               661                   25   
1    ...                  91               688                   52   
3    ...                  70               820                   42   
4    ...                  86               996                   55   
5    ...                  93              1245                   59   
..   ...                 ...               ...                  ...   
290  ...                  92               156                   47   
291  ...                  89               397                   44   
292  ...                  93               578                   59   
293  ...                  78               729                   50   
297  ...                  72               935                   25   

    NumMerchItemsOnAmazon GoogleSearchIndex2024 InstagramFanPages  \
0                    2524                    68               298   
1                    4202                    49               133   
3                    1951                    73               138   
4                    3958                    34               155   
5                     555                    67               216   
..                    ...                   ...               ...   
290                  4440                    88               248   
291                   493                    61               156   
292                   523                    46                91   
293                  4350                    74               241   
297                  1815                    53                53   

    TikTokHashtagViewsMillions  \
0                          481   
1                          619   
3                          697   
4                          200   
5                          454   
..                         ...   
290                        386   
291                        237   
292                        140   
293                        977   
297           

In [ ]:
import pandas as pd
emp=pd.read_csv("/content/employees.csv")
print(emp)

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30   Chicago   80000
2  Charlie   28    Boston   75000


In [ ]:
emp[emp["City"]=="New York"]

Name  Age      City  Salary
0  Alice   25  New York   70000

In [ ]:
emp[emp["Age"]>25]

Name  Age     City  Salary
1      Bob   30  Chicago   80000
2  Charlie   28   Boston   75000

In [ ]:
emp[(emp["Salary"]>75000)&(emp["Age"]>25)]

Name  Age     City  Salary
1  Bob   30  Chicago   80000

In [ ]:
emp[(emp["City"]=="Chicago")|(emp["Age"]>25)]

Name  Age     City  Salary
1      Bob   30  Chicago   80000
2  Charlie   28   Boston   75000

In [ ]:
emp[~(emp["City"]=="Boston")]

Name  Age      City  Salary
0  Alice   25  New York   70000
1    Bob   30   Chicago   80000

In [ ]:
emp[emp["Age"].between(30,35)]

Name  Age     City  Salary
1  Bob   30  Chicago   80000

In [ ]:
emp[(emp["Age"]<30)&(emp["Age"]>25)]

Name  Age    City  Salary
2  Charlie   28  Boston   75000

In [ ]:
emp[emp["Name"].str.contains("Bob")]

Name  Age     City  Salary
1  Bob   30  Chicago   80000

In [ ]:
emp[emp["Name"].str.startswith("A")]

Name  Age      City  Salary
0  Alice   25  New York   70000

In [ ]:
emp[emp["Name"].str.endswith("e")]

Name  Age      City  Salary
0    Alice   25  New York   70000
2  Charlie   28    Boston   75000

In [ ]:
emp[emp["City"].str.contains("New")]

Name  Age      City  Salary
0  Alice   25  New York   70000

In [ ]:
emp[emp["Age"].isnull()]

Empty DataFrame
Columns: [Name, Age, City, Salary]
Index: []

In [ ]:
emp[emp["Age"].notnull()]

Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30   Chicago   80000
2  Charlie   28    Boston   75000

In [ ]:
dataemp={"Name":["Alice","Bob","Charlie","Israa","Itaa","Muni","Sam","MD",None],
         "Age":[25,30,28,24,None,28,40,32,29],
         "Salary":[70000,80000,75000,90000,2000,None,80000,120000,4000],
         "City":["New York","Chicago","Boston","Muscat","Muscat",None,"Dubai","Dubai","DC"],
         "Status":["Single","Single","Married","Married","Single","Married","Married","Married","Single"]}
emp=pd.DataFrame(dataemp)
print(emp)


      Name   Age    Salary      City   Status
0    Alice  25.0   70000.0  New York   Single
1      Bob  30.0   80000.0   Chicago   Single
2  Charlie  28.0   75000.0    Boston  Married
3    Israa  24.0   90000.0    Muscat  Married
4     Itaa   NaN    2000.0    Muscat   Single
5     Muni  28.0       NaN      None  Married
6      Sam  40.0   80000.0     Dubai  Married
7       MD  32.0  120000.0     Dubai  Married
8     None  29.0    4000.0        DC   Single


In [ ]:
emp.to_csv("emp_data.csv",index=False)

In [ ]:
emp[emp["Age"].isnull()]

Name  Age  Salary    City  Status
4  Itaa  NaN  2000.0  Muscat  Single

In [ ]:
emp[emp["Salary"].notnull()]

Name   Age    Salary      City   Status
0    Alice  25.0   70000.0  New York   Single
1      Bob  30.0   80000.0   Chicago   Single
2  Charlie  28.0   75000.0    Boston  Married
3    Israa  24.0   90000.0    Muscat  Married
4     Itaa   NaN    2000.0    Muscat   Single
6      Sam  40.0   80000.0     Dubai  Married
7       MD  32.0  120000.0     Dubai  Married
8     None  29.0    4000.0        DC   Single

In [ ]:
mask=emp["City"]=="Dubai"
emp[mask]

Name   Age    Salary   City   Status
6  Sam  40.0   80000.0  Dubai  Married
7   MD  32.0  120000.0  Dubai  Married

In [ ]:
print(emp)

      Name   Age    Salary      City   Status
0    Alice  25.0   70000.0  New York   Single
1      Bob  30.0   80000.0   Chicago   Single
2  Charlie  28.0   75000.0    Boston  Married
3    Israa  24.0   90000.0    Muscat  Married
4     Itaa   NaN    2000.0    Muscat   Single
5     Muni  28.0       NaN      None  Married
6      Sam  40.0   80000.0     Dubai  Married
7       MD  32.0  120000.0     Dubai  Married
8     None  29.0    4000.0        DC   Single


In [ ]:
emp.drop(columns=["Status"],inplace=True)
print(emp)

      Name   Age    Salary      City
0    Alice  25.0   70000.0  New York
1      Bob  30.0   80000.0   Chicago
2  Charlie  28.0   75000.0    Boston
3    Israa  24.0   90000.0    Muscat
4     Itaa   NaN    2000.0    Muscat
5     Muni  28.0       NaN      None
6      Sam  40.0   80000.0     Dubai
7       MD  32.0  120000.0     Dubai
8     None  29.0    4000.0        DC


In [ ]:
emp["Bonus"]=emp["Salary"]*0.1
print(emp)

      Name   Age    Salary      City    Bonus
0    Alice  25.0   70000.0  New York   7000.0
1      Bob  30.0   80000.0   Chicago   8000.0
2  Charlie  28.0   75000.0    Boston   7500.0
3    Israa  24.0   90000.0    Muscat   9000.0
4     Itaa   NaN    2000.0    Muscat    200.0
5     Muni  28.0       NaN      None      NaN
6      Sam  40.0   80000.0     Dubai   8000.0
7       MD  32.0  120000.0     Dubai  12000.0
8     None  29.0    4000.0        DC    400.0


In [ ]:
emp["Age"]=emp["Age"]+1
print(emp)

      Name   Age    Salary      City    Bonus
0    Alice  26.0   70000.0  New York   7000.0
1      Bob  31.0   80000.0   Chicago   8000.0
2  Charlie  29.0   75000.0    Boston   7500.0
3    Israa  25.0   90000.0    Muscat   9000.0
4     Itaa   NaN    2000.0    Muscat    200.0
5     Muni  29.0       NaN      None      NaN
6      Sam  41.0   80000.0     Dubai   8000.0
7       MD  33.0  120000.0     Dubai  12000.0
8     None  30.0    4000.0        DC    400.0


In [ ]:
emp.rename(columns={"Salary":"Income"}, inplace=True)
print(emp)

      Name   Age    Income      City    Bonus
0    Alice  26.0   70000.0  New York   7000.0
1      Bob  31.0   80000.0   Chicago   8000.0
2  Charlie  29.0   75000.0    Boston   7500.0
3    Israa  25.0   90000.0    Muscat   9000.0
4     Itaa   NaN    2000.0    Muscat    200.0
5     Muni  29.0       NaN      None      NaN
6      Sam  41.0   80000.0     Dubai   8000.0
7       MD  33.0  120000.0     Dubai  12000.0
8     None  30.0    4000.0        DC    400.0


In [ ]:
emp.drop("Bonus",axis=1,inplace=True)
print(emp)

      Name   Age    Income      City
0    Alice  26.0   70000.0  New York
1      Bob  31.0   80000.0   Chicago
2  Charlie  29.0   75000.0    Boston
3    Israa  25.0   90000.0    Muscat
4     Itaa   NaN    2000.0    Muscat
5     Muni  29.0       NaN      None
6      Sam  41.0   80000.0     Dubai
7       MD  33.0  120000.0     Dubai
8     None  30.0    4000.0        DC


In [ ]:
empclean=emp.dropna()
print(empclean)

      Name   Age    Income      City
0    Alice  26.0   70000.0  New York
1      Bob  31.0   80000.0   Chicago
2  Charlie  29.0   75000.0    Boston
3    Israa  25.0   90000.0    Muscat
6      Sam  41.0   80000.0     Dubai
7       MD  33.0  120000.0     Dubai


In [ ]:
empsort=emp.sort_values("Age")
print(empsort)

      Name   Age    Income      City
3    Israa  25.0   90000.0    Muscat
0    Alice  26.0   70000.0  New York
2  Charlie  29.0   75000.0    Boston
5     Muni  29.0       NaN      None
8     None  30.0    4000.0        DC
1      Bob  31.0   80000.0   Chicago
7       MD  33.0  120000.0     Dubai
6      Sam  41.0   80000.0     Dubai
4     Itaa   NaN    2000.0    Muscat


In [ ]:
empsort=emp.sort_values("Income",ascending=False)
print(empsort)

      Name   Age    Income      City
7       MD  33.0  120000.0     Dubai
3    Israa  25.0   90000.0    Muscat
6      Sam  41.0   80000.0     Dubai
1      Bob  31.0   80000.0   Chicago
2  Charlie  29.0   75000.0    Boston
0    Alice  26.0   70000.0  New York
8     None  30.0    4000.0        DC
4     Itaa   NaN    2000.0    Muscat
5     Muni  29.0       NaN      None


In [ ]:
city_salary=emp.groupby("City")["Income"].mean()
print(city_salary)

City
Boston       75000.0
Chicago      80000.0
DC            4000.0
Dubai       100000.0
Muscat       46000.0
New York     70000.0
Name: Income, dtype: float64


In [ ]:
city_count=emp["City"].value_counts()
print(city_count)

City
Dubai       2
Muscat      2
Chicago     1
New York    1
Boston      1
DC          1
Name: count, dtype: int64


In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/sample_sales_data.csv')
print(df)

    OrderID CustomerName     Category  OrderDate  Quantity   Price  \
0   ORD0001       Hannah        Books   1/1/2025         6  331.73   
1   ORD0002       Edward        Books   1/2/2025         3  310.03   
2   ORD0003        Alice     Clothing   1/3/2025         9  176.17   
3   ORD0004       Hannah  Electronics   1/4/2025         3   79.97   
4   ORD0005       George         Home   1/5/2025         7  406.03   
..      ...          ...          ...        ...       ...     ...   
95  ORD0096        Diana     Clothing   4/6/2025         5  368.23   
96  ORD0097          Bob        Books   4/7/2025         8  360.17   
97  ORD0098        Diana     Clothing   4/8/2025         9   29.97   
98  ORD0099        Alice         Home   4/9/2025         5  465.20   
99  ORD0100      Charlie        Books  4/10/2025         9   41.55   

    TotalAmount     Status  
0       1990.38   Canceled  
1        930.09  Completed  
2       1585.53   Canceled  
3        239.91    Pending  
4       2842.2

In [ ]:
total = df[df['TotalAmount'] > 500]
print(total)

electronics= df[df['Category'] == 'Electronics']
print(electronics)


    OrderID CustomerName     Category OrderDate  Quantity   Price  \
0   ORD0001       Hannah        Books  1/1/2025         6  331.73   
1   ORD0002       Edward        Books  1/2/2025         3  310.03   
2   ORD0003        Alice     Clothing  1/3/2025         9  176.17   
4   ORD0005       George         Home  1/5/2025         7  406.03   
5   ORD0006      Charlie        Books  1/6/2025         9  390.27   
..      ...          ...          ...       ...       ...     ...   
92  ORD0093      Charlie  Electronics  4/3/2025         5  118.72   
94  ORD0095        Alice        Books  4/5/2025         4  143.94   
95  ORD0096        Diana     Clothing  4/6/2025         5  368.23   
96  ORD0097          Bob        Books  4/7/2025         8  360.17   
98  ORD0099        Alice         Home  4/9/2025         5  465.20   

    TotalAmount     Status  
0       1990.38   Canceled  
1        930.09  Completed  
2       1585.53   Canceled  
4       2842.21   Canceled  
5       3512.43  Completed

In [ ]:

clothing = df[(df['Category'] == 'Clothing') & (df['Status'] == 'Completed')]
print(clothing)

pending = df[(df['Quantity'] > 5) | (df['Status'] == 'Pending')]
print(pending)


    OrderID CustomerName  Category  OrderDate  Quantity   Price  TotalAmount  \
17  ORD0018       George  Clothing  1/18/2025        10  267.14      2671.40   
18  ORD0019        Alice  Clothing        NaN         3  227.82       683.46   
23  ORD0024          Bob  Clothing  1/24/2025         5  293.58      1467.90   
26  ORD0027      Charlie  Clothing  1/27/2025         3  432.17      1296.51   
54  ORD0055          Bob  Clothing  2/24/2025         9  142.33      1280.97   
58  ORD0059        Fiona  Clothing  2/28/2025         7  161.67      1131.69   
66  ORD0067        Diana  Clothing   3/8/2025         3  467.02      1401.06   
76  ORD0077        Alice  Clothing  3/18/2025         9  163.71      1473.39   
77  ORD0078        Alice  Clothing  3/19/2025         2   25.33        50.66   
78  ORD0079          NaN  Clothing  3/20/2025         6   80.48       482.88   
95  ORD0096        Diana  Clothing   4/6/2025         5  368.23      1841.15   

       Status  
17  Completed  
18  Com

In [ ]:
orders = df[(df['TotalAmount'] >= 200) & (df['TotalAmount'] <= 1000)]
print(orders)


    OrderID CustomerName     Category  OrderDate  Quantity   Price  \
1   ORD0002       Edward        Books   1/2/2025         3  310.03   
3   ORD0004       Hannah  Electronics   1/4/2025         3   79.97   
8   ORD0009      Charlie  Electronics   1/9/2025         2  222.30   
11  ORD0012        Alice         Home  1/12/2025         4  157.95   
12  ORD0013        Fiona     Clothing  1/13/2025         9   44.52   
13  ORD0014      Charlie         Home  1/14/2025         2  108.11   
15  ORD0016       Hannah     Clothing  1/16/2025         1  241.91   
18  ORD0019        Alice     Clothing        NaN         3  227.82   
19  ORD0020       George     Clothing  1/20/2025         2  462.31   
21  ORD0022        Fiona         Home  1/22/2025         9   62.70   
31  ORD0032          Bob        Books   2/1/2025         6  149.55   
37  ORD0038       Hannah         Home   2/7/2025         6  135.51   
40  ORD0041       George     Clothing  2/10/2025         5  123.01   
42  ORD0043        A

In [ ]:
df[df['CustomerName'].str.startswith('A', na=False)]

OrderID CustomerName     Category  OrderDate  Quantity   Price  \
2   ORD0003        Alice     Clothing   1/3/2025         9  176.17   
9   ORD0010        Alice         Home  1/10/2025         3  476.14   
11  ORD0012        Alice         Home  1/12/2025         4  157.95   
18  ORD0019        Alice     Clothing        NaN         3  227.82   
42  ORD0043        Alice     Clothing  2/12/2025         9   92.59   
55  ORD0056        Alice     Clothing  2/25/2025         6  161.37   
64  ORD0065        Alice        Books   3/6/2025         5  469.38   
76  ORD0077        Alice     Clothing  3/18/2025         9  163.71   
77  ORD0078        Alice     Clothing  3/19/2025         2   25.33   
79  ORD0080        Alice     Clothing  3/21/2025         6  244.66   
81  ORD0082        Alice         Home  3/23/2025         3  346.71   
84  ORD0085        Alice         Home  3/26/2025         1  124.89   
86  ORD0087        Alice  Electronics  3/28/2025         3   86.55   
89  ORD0090        Alice        Books  3/31/2025         1  215.99   
93  ORD0094        Alice  Electronics   4/4/2025         2   60.11   
94  ORD0095        Alice        Books   4/5/2025         4  143.94   
98  ORD0099        Alice         Home   4/9/2025         5  465.20   

    TotalAmount     Status  
2       1585.53   Canceled  
9       1428.42    Pending  
11       631.80  Completed  
18       683.46  Completed  
42       833.31    Pending  
55       968.22    Pending  
64      2346.90  Completed  
76      1473.39  Completed  
77        50.66  Completed  
79      1467.96    Pending  
81      1040.13    Pending  
84       124.89   Canceled  
86       259.65    Pending  
89       215.99   Canceled  
93       120.22   Canceled  
94       575.76   Canceled  
98      2326.00    Pending

In [ ]:
df[df['Category'].str.contains('Home')]


OrderID CustomerName Category  OrderDate  Quantity   Price  TotalAmount  \
4   ORD0005       George     Home   1/5/2025         7  406.03      2842.21   
9   ORD0010        Alice     Home  1/10/2025         3  476.14      1428.42   
11  ORD0012        Alice     Home  1/12/2025         4  157.95       631.80   
13  ORD0014      Charlie     Home  1/14/2025         2  108.11       216.22   
14  ORD0015      Charlie     Home  1/15/2025        10  381.90      3819.00   
21  ORD0022        Fiona     Home  1/22/2025         9   62.70       564.30   
24  ORD0025       Edward     Home  1/25/2025        10  262.13      2621.30   
25  ORD0026      Charlie     Home  1/26/2025         4  318.66      1274.64   
30  ORD0031        Diana     Home  1/31/2025         2   61.32       122.64   
32  ORD0033       Hannah     Home   2/2/2025         4  263.42      1053.68   
37  ORD0038       Hannah     Home   2/7/2025         6  135.51       813.06   
44  ORD0045       Hannah     Home  2/14/2025         6  418.15      2508.90   
45  ORD0046       George     Home  2/15/2025         2  119.26       238.52   
47  ORD0048       Hannah     Home        NaN         8   23.50       188.00   
50  ORD0051       Edward     Home  2/20/2025         5  276.70      1383.50   
52  ORD0053       Edward     Home  2/22/2025         2  261.63       523.26   
53  ORD0054          Bob     Home  2/23/2025         5  465.84      2329.20   
63  ORD0064          Bob     Home   3/5/2025         5  367.43      1837.15   
68  ORD0069       Edward     Home  3/10/2025         6  201.93      1211.58   
71  ORD0072        Fiona     Home  3/13/2025         3  204.01       612.03   
72  ORD0073       Hannah     Home  3/14/2025         9  203.84      1834.56   
81  ORD0082        Alice     Home  3/23/2025         3  346.71      1040.13   
84  ORD0085        Alice     Home  3/26/2025         1  124.89       124.89   
98  ORD0099        Alice     Home   4/9/2025         5  465.20      2326.00   

       Status  
4    Canceled  
9     Pending  
11  Completed  
13  Completed  
14   Canceled  
21    Pending  
24   Canceled  
25    Pending  
30  Completed  
32   Canceled  
37   Canceled  
44    Pending  
45  Completed  
47    Pending  
50  Completed  
52    Pending  
53  Completed  
63  Completed  
68    Pending  
71  Completed  
72   Canceled  
81    Pending  
84   Canceled  
98    Pending

In [ ]:
df[df["Category"].notnull()]

OrderID CustomerName     Category  OrderDate  Quantity   Price  \
0   ORD0001       Hannah        Books   1/1/2025         6  331.73   
1   ORD0002       Edward        Books   1/2/2025         3  310.03   
2   ORD0003        Alice     Clothing   1/3/2025         9  176.17   
3   ORD0004       Hannah  Electronics   1/4/2025         3   79.97   
4   ORD0005       George         Home   1/5/2025         7  406.03   
..      ...          ...          ...        ...       ...     ...   
95  ORD0096        Diana     Clothing   4/6/2025         5  368.23   
96  ORD0097          Bob        Books   4/7/2025         8  360.17   
97  ORD0098        Diana     Clothing   4/8/2025         9   29.97   
98  ORD0099        Alice         Home   4/9/2025         5  465.20   
99  ORD0100      Charlie        Books  4/10/2025         9   41.55   

    TotalAmount     Status  
0       1990.38   Canceled  
1        930.09  Completed  
2       1585.53   Canceled  
3        239.91    Pending  
4       2842.21   Canceled  
..          ...        ...  
95      1841.15  Completed  
96      2881.36  Completed  
97       269.73   Canceled  
98      2326.00    Pending  
99       373.95    Pending  

[100 rows x 8 columns]

In [ ]:
df[df["Category"].isnull()]

Empty DataFrame
Columns: [OrderID, CustomerName, Category, OrderDate, Quantity, Price, TotalAmount, Status]
Index: []

In [ ]:
df[(df["Category"]=="Clothing")&(df["Status"]=="Completed")]

OrderID CustomerName  Category  OrderDate  Quantity   Price  TotalAmount  \
17  ORD0018       George  Clothing  1/18/2025        10  267.14      2671.40   
18  ORD0019        Alice  Clothing        NaN         3  227.82       683.46   
23  ORD0024          Bob  Clothing  1/24/2025         5  293.58      1467.90   
26  ORD0027      Charlie  Clothing  1/27/2025         3  432.17      1296.51   
54  ORD0055          Bob  Clothing  2/24/2025         9  142.33      1280.97   
58  ORD0059        Fiona  Clothing  2/28/2025         7  161.67      1131.69   
66  ORD0067        Diana  Clothing   3/8/2025         3  467.02      1401.06   
76  ORD0077        Alice  Clothing  3/18/2025         9  163.71      1473.39   
77  ORD0078        Alice  Clothing  3/19/2025         2   25.33        50.66   
78  ORD0079          NaN  Clothing  3/20/2025         6   80.48       482.88   
95  ORD0096        Diana  Clothing   4/6/2025         5  368.23      1841.15   

       Status  
17  Completed  
18  Completed  
23  Completed  
26  Completed  
54  Completed  
58  Completed  
66  Completed  
76  Completed  
77  Completed  
78  Completed  
95  Completed

In [ ]:
scolumns = df[['OrderID', 'CustomerName', 'TotalAmount']]
print(scolumns)

    OrderID CustomerName  TotalAmount
0   ORD0001       Hannah      1990.38
1   ORD0002       Edward       930.09
2   ORD0003        Alice      1585.53
3   ORD0004       Hannah       239.91
4   ORD0005       George      2842.21
..      ...          ...          ...
95  ORD0096        Diana      1841.15
96  ORD0097          Bob      2881.36
97  ORD0098        Diana       269.73
98  ORD0099        Alice      2326.00
99  ORD0100      Charlie       373.95

[100 rows x 3 columns]


In [ ]:
mask=df["Price"]>100
df[mask]

OrderID CustomerName     Category OrderDate  Quantity   Price  \
0   ORD0001       Hannah        Books  1/1/2025         6  331.73   
1   ORD0002       Edward        Books  1/2/2025         3  310.03   
2   ORD0003        Alice     Clothing  1/3/2025         9  176.17   
4   ORD0005       George         Home  1/5/2025         7  406.03   
5   ORD0006      Charlie        Books  1/6/2025         9  390.27   
..      ...          ...          ...       ...       ...     ...   
92  ORD0093      Charlie  Electronics  4/3/2025         5  118.72   
94  ORD0095        Alice        Books  4/5/2025         4  143.94   
95  ORD0096        Diana     Clothing  4/6/2025         5  368.23   
96  ORD0097          Bob        Books  4/7/2025         8  360.17   
98  ORD0099        Alice         Home  4/9/2025         5  465.20   

    TotalAmount     Status  
0       1990.38   Canceled  
1        930.09  Completed  
2       1585.53   Canceled  
4       2842.21   Canceled  
5       3512.43  Completed  
..          ...        ...  
92       593.60  Completed  
94       575.76   Canceled  
95      1841.15  Completed  
96      2881.36  Completed  
98      2326.00    Pending  

[82 rows x 8 columns]

In [ ]:
df.loc[df['TotalAmount'] > 500, ['OrderID', 'Status']]

OrderID     Status
0   ORD0001   Canceled
1   ORD0002  Completed
2   ORD0003   Canceled
4   ORD0005   Canceled
5   ORD0006  Completed
..      ...        ...
92  ORD0093  Completed
94  ORD0095   Canceled
95  ORD0096  Completed
96  ORD0097  Completed
98  ORD0099    Pending

[72 rows x 2 columns]

In [ ]:
df.iloc[:10][['OrderID', 'TotalAmount']]

OrderID  TotalAmount
0  ORD0001      1990.38
1  ORD0002       930.09
2  ORD0003      1585.53
3  ORD0004       239.91
4  ORD0005      2842.21
5  ORD0006      3512.43
6  ORD0007      1079.33
7  ORD0008      2668.60
8  ORD0009       444.60
9  ORD0010      1428.42

In [ ]:
df.drop(columns=['Status'])

OrderID CustomerName     Category  OrderDate  Quantity   Price  \
0   ORD0001       Hannah        Books   1/1/2025         6  331.73   
1   ORD0002       Edward        Books   1/2/2025         3  310.03   
2   ORD0003        Alice     Clothing   1/3/2025         9  176.17   
3   ORD0004       Hannah  Electronics   1/4/2025         3   79.97   
4   ORD0005       George         Home   1/5/2025         7  406.03   
..      ...          ...          ...        ...       ...     ...   
95  ORD0096        Diana     Clothing   4/6/2025         5  368.23   
96  ORD0097          Bob        Books   4/7/2025         8  360.17   
97  ORD0098        Diana     Clothing   4/8/2025         9   29.97   
98  ORD0099        Alice         Home   4/9/2025         5  465.20   
99  ORD0100      Charlie        Books  4/10/2025         9   41.55   

    TotalAmount  
0       1990.38  
1        930.09  
2       1585.53  
3        239.91  
4       2842.21  
..          ...  
95      1841.15  
96      2881.36  
97       269.73  
98      2326.00  
99       373.95  

[100 rows x 7 columns]

In [ ]:
amount_500=df[df["TotalAmount"]>500]
print(amount_500)

    OrderID CustomerName     Category OrderDate  Quantity   Price  \
0   ORD0001       Hannah        Books  1/1/2025         6  331.73   
1   ORD0002       Edward        Books  1/2/2025         3  310.03   
2   ORD0003        Alice     Clothing  1/3/2025         9  176.17   
4   ORD0005       George         Home  1/5/2025         7  406.03   
5   ORD0006      Charlie        Books  1/6/2025         9  390.27   
..      ...          ...          ...       ...       ...     ...   
92  ORD0093      Charlie  Electronics  4/3/2025         5  118.72   
94  ORD0095        Alice        Books  4/5/2025         4  143.94   
95  ORD0096        Diana     Clothing  4/6/2025         5  368.23   
96  ORD0097          Bob        Books  4/7/2025         8  360.17   
98  ORD0099        Alice         Home  4/9/2025         5  465.20   

    TotalAmount     Status  
0       1990.38   Canceled  
1        930.09  Completed  
2       1585.53   Canceled  
4       2842.21   Canceled  
5       3512.43  Completed

In [ ]:
amount_500==('high_value_orders.csv', index=False)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (<ipython-input-106-b5b2bfd1ed36>, line 1)

In [ ]:
# prompt: make skewness graph

import pandas as pd
import matplotlib.pyplot as plt

# Assuming your data is in a DataFrame called 'df'
# Replace 'your_column_name' with the actual column name you want to analyze
data = pd.read_csv('/content/sample_data')

# Calculate skewness
skewness = data['TotalAmount'].skew()

# Create the skewness plot
plt.figure(figsize=(8, 6))
plt.hist(data['TotalAmount'], bins=30, edgecolor='black')  # Adjust bins as needed
plt.title(f"Skewness of TotalAmount: {skewness:.2f}")
plt.xlabel('TotalAmount')
plt.ylabel('Frequency')

# Add a vertical line for the mean
plt.axvline(data['TotalAmount'].mean(), color='red', linestyle='dashed', linewidth=1, label='Mean')

plt.legend()
plt.grid(True)
plt.show()


IsADirectoryError: [Errno 21] Is a directory: '/content/sample_data'